### ISSUE TITLE
Design ideas for labs-site when migrating webpage.

### ISSUE THREAD

**Issue by juanis2112** [Quansight-Labs/quansight-labs-site#215]
These are some of the design ideas from the issues that are open to take into account for the migration that @trallard will be working on. 

- [x] Add comments boxes to the bottom of the blogposts #18 
- [ ] Create a graphical element for the front page #99 
- [x] Increase the site's font from 14px to at least 16px #109  #111 
- [x] Change color of visited links ir order to be more visible #110 
- [ ] Add sidebar with years (2019, 2020, 2021) to easily navigate through the content #119  
- [ ] Add sidebar with all tags and all authors to easily navigate through the content by clicking on item and filtering the content (?) #119 #204 
- [ ] Change the gray code block background to either match the white background, or make it a much lighter gray #176 
- [x] Darken or brighten the comment text color #176 
- [ ] Get a labs.quansight.com -> labs.quansight.org redirect #185

**Comment by trallard** [comment]
Referencig #121  as Aaron was working on this

**Comment by Carreau** [comment]
#223  adds comment boxes using utterances.
